#!/usr/bin/env bash
# install nginx and config
apt-get -y update
apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart

