#!/usr/bin/env bash
# add a 301 redirection
# Update package list
sudo apt-get update || { echo "Failed to update package list"; exit 1; }

# Install Nginx
sudo apt-get install -y nginx || { echo "Failed to install Nginx"; exit 1; }

# Create a custom HTML page
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Configure Nginx (port 80)
sudo bash -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=7VAI73roXaY&list=PPSV;
    }

}" > /etc/nginx/sites-available/default' || { echo "Failed to configure Nginx"; exit 1; }

# Restart Nginx
sudo service nginx restart || { echo "Failed to restart Nginx"; exit 1; }

# Wait for Nginx to be fully restarted
while ! curl -s http://localhost &> /dev/null; do
    sleep 1
done

# Check if Nginx returns the expected content
curl_output=$(curl -s http://localhost/redirect_me)
if [[ "$curl_output" == *"301 Moved Permanently"* && "$curl_output" == *"Location: http://example.com/destination-page"* ]]; then
    echo "Nginx configured successfully for redirection!"
else
    echo "Nginx redirection configuration check failed."
fi

